name: Test the Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: Aetheron/github_release_to_teamwork_notebook@main
        with:
          notebook_id: 31563
          domain: fusionary.teamwork.com
          api_key: ${{ secrets.TEAMWORK_API_KEY }}
